name: Call Build
on:
  push:
    branches: [main]
jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      app_name: "myapp"
      environment: "production"
    secrets:
      docker_token: ${{ secrets.DOCKER_TOKEN }}
