name: Conditional Workflow

on:
 push:
   branches: [main]
 pull_request:
   branches: [main]
 workflow_dispatch:

jobs:
  on_main:
   runs-on: ubuntu-latest
   steps:
     - name: runs only on main-branch
       if: github.ref == 'refs/heads/main'
       run: |
        echo "Runs only on main branch"
        # exit 1

     - name: runs when the previous step fails
       if: failure()
       run: echo "Previous step has been failed."

  # on-push:
  #   if: github.event_name != 'pull_request'
  #   runs-on: ubuntu-latest 
  #   steps:
  #     - name: runs only on push events
  #       run: echo "Only run on push events"
        
      # - name: continue-on-error
      #   run: |
      #     echo "The step results in failure"
      #     exit 1
      #   continue-on-error: true
