name: External Trigger
on:
  repository_dispatch:
    types: [ deploy-request ]
jobs:
  depoy:
    runs-on: ubuntu-latest
    steps:
      - name: Print the Environment
        run: |
            echo " The payload environment is : ${{ github.event.client_payload.environment }}"

 
  
