name: Reusable Build
on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      environment:
        required: false
        type: string
        default: staging
    secrets:
      docker_token:
        required: true
    outputs:
      build-task:
        description: This is the first output string
        value: ${{ jobs.build.outputs.outputs1 }}
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      outputs1: ${{ steps.set-version.outputs.build_version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Print Info
        run: echo "The ${{ inputs.app_name }} is for ${{ inputs.environment }}"
      - name: Docker Token
        run: |
          if [ -n "${{ secrets.docker_token }}" ]; then   
            echo "Docker token is set: true"
           fi   

      - name: Generate a version
        id: set-version
        run: |
         BUILD_VERSION="v1.0-${GITHUB_SHA::7}"
         echo "build_version=$BUILD_VERSION" >> $GITHUB_OUTPUT
         echo "Generated build version: $BUILD_VERSION"
