name: Secret Message
on:
 workflow_dispatch:
jobs:
  print-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Created Secret
        run: echo ${{secrets.MY_SECRET_MESSAGE}}
      - name: Check Secret
        run: |
             if [ ! ${{secrets.MY_SECRET_MESSAGE}}]; then
               echo "No secret message"
             elif:  
                 echo "NOT FOUND"
      - name: Print Secret
        run: echo "My secret message is ${{secrets.MY_SECRET_MESSAGE}}"
                  
