name: Smart Triggers
on:  
  push:
    paths-ignore:
     - '*.md'
     - 'docs/**'  
jobs:
   check-path:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Print message 
        run: echo "Workflow worked as no change is done in .md,docs/**" 
          




      
