name: Python Script Checker

on:
  workflow_dispatch:

jobs:
  script-check:             # Job name
    runs-on: ubuntu-latest  # Runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install the dependencies
        run: pip install -r requirements.txt || echo "No requirements"

      - name: Run Python script
        run: python my-script.py
