name: Upload Artifacts
on:
  workflow_dispatch:
jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        run: actions/checkout@v4
      - name: Create Folder
        run:  |
            mkdir -p my-folder/output.txt
            echo "This is the file created for artifact upload" > my-folder/output.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact-folder
          path: my-folder/output.txt
