name: Use Setup and Greet

on:
  push:
    branches: [main]

jobs:
  greet-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Setup and Greet
        uses: ./.github/actions/setup-and-greet
        with:
          name: "ABC"
          language: "en"

      - name: Print Action Output
        run:  echo "Greeted value: ${{ steps.greet.outputs.greeted }}"
