name: Use Setup and Greet
on:
  workflow_dispatch:
  # push:
  #   branches: [main]

jobs:
  greet-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Setup and Greet
        id: greet
        uses: ./.github/actions/setup-and-greet
        with:
          name: "ABC"
          language: "en"

      - name: Print the Action Output
        run:  |
            echo "Greeted value: ${{ steps.greet.outputs.greeted }}"
